version: '2'
services:
  backend:
    image: map-app/backend
    ports:
    - "8080:8080"
    depends_on:
    - db
  db:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mapdb
  web:
    build: frontend/map-app-gui
    ports:
     - "4200:4200"
    depends_on:
     - backend